### PR TITLE
Design Muscle-1 Done

### PR DESCRIPTION
**Pull request by JackofAllCodez**
Issue: 133

image

### CODE REVIEW

**Comment by JackofAllCodez** [comment]
Done with the changes mam 👍🏻

**Comment by Saishreekouda** [comment]
@JackofAllCodez can you join discord vc?

**Comment by JackofAllCodez** [comment]
Sorry mam, I didnt see the message. 
Is 6 pm OK mam?

**Comment by Saishreekouda** [comment]
hey can you join today? @JackofAllCodez

**Pull request merged**
