### PR TITLE
logo design task done

### PR DESCRIPTION
**Pull request by itsaman1825**
issue: 58

### CODE REVIEW

**Comment by Saishreekouda** [comment]
@itsaman1825 Try a more minimal approach and use colors that will go with the app.

**Comment by itsaman1825** [comment]
Sorry but i am not aware of the app. Can you please provide me any link or
any image of the app?

**Comment by Saishreekouda** [comment]
@itsaman1825 I meant it should go with the theme of the app's idea DonateASmile. You can read more about it from here:
https://github.com/opencodeiiita/DonateASmile/blob/main/README.md

**Comment by itsaman1825** [comment]
@Saishreekouda changes done. please review.

**Comment by Saishreekouda** [comment]
@itsaman1825 try a different approach as this looks kinda creepy

**Comment by itsaman1825** [comment]
@Saishreekouda changes done. please review once.

**Comment by Saishreekouda** [comment]
@itsaman1825 make the background white and use colors from https://colorhunt.co/palette/f7a4a4febe8cfffbc1b6e2a1 this color palette.

**Comment by itsaman1825** [comment]
done

**Comment by itsaman1825** [comment]
@Saishreekouda proposed changes done

**Pull request merged**
