### PR TITLE
Logo Design

### PR DESCRIPTION
**Pull request by anshgeez31**
Issue: 58
image

### CODE REVIEW

**Comment by Saishreekouda** [comment]
Hey @anshgeez31 this logo doesnt signify the donation aspect of the app anywhere so if you could try a newer approach that'd be great.

**Comment by anshgeez31** [comment]
@Saishreekouda updated logo. Now please review this.

**Comment by Saishreekouda** [comment]
@anshgeez31 it looks like the logo has too many elements so just remove the smiley face. You have used the pen tool to make the vector but it has some sharp edges and to resolve that you can watch this video- https://www.youtube.com/watch?v=d78yo84tnfA. Ping me on discord for any doubts.

**Comment by anshgeez31** [comment]
@Saishreekouda Now have a look again. I have removed smiley face and have curved the sharpened area.

**Pull request merged**
