### PR TITLE
Design muscles 2

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 167

### CODE REVIEW

**Comment by Saishreekouda** [comment]
@SanyamAgrawal07 check your figma file, added a few comments

**Comment by SanyamAgrawal07** [comment]
@Saishreekouda Please review the changes

**Comment by Saishreekouda** [comment]
@SanyamAgrawal07 one final change in your file, please check

**Comment by SanyamAgrawal07** [comment]
@Saishreekouda Yea made the change please review

**Pull request merged**
