### PR TITLE
Vector design task

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 107

vector design 2

### CODE REVIEW

**Comment by SanyamAgrawal07** [comment]
@Saishreekouda I have added a different vector please review

**Comment by Saishreekouda** [comment]
@SanyamAgrawal07 i have added a comment please check (in figma file)

**Comment by SanyamAgrawal07** [comment]
@Saishreekouda any more changes?(I have resolved the figma comment)

**Comment by Saishreekouda** [comment]
its okay now

**Pull request merged**
