### PR TITLE
short graphic task

### PR DESCRIPTION
**Pull request by 88oo**
Issue: 117

### CODE REVIEW

**Comment by Koshal7** [comment]
image

**Comment by Saishreekouda** [comment]
hey @Koshal7 if you could have a sneaker related logo it would be better.

**Comment by Koshal7** [comment]
It's a logo, do you want me to add a sneaker to make it look like a sneaker logo? @Saishreekouda pls let me know what changes I can do.

**Comment by Saishreekouda** [comment]
@Koshal7 it would be better if you would inculcate a sneaker vector in the logo as when brands start off they try to showcase their product in their logo and if the brand happens to become something big then their logo can be something else without the product

**Pull request merged**
