### PR TITLE
Design Muscle -1

### PR DESCRIPTION
**Pull request by JahnaviGadde**
Issue: 133

### CODE REVIEW

**Comment by Saishreekouda** [comment]
@JahnaviGadde can you join discord vc?

**Comment by JahnaviGadde** [comment]
changes done 👍

**Comment by Saishreekouda** [comment]
@JahnaviGadde have added a few comments in your file, please check

**Comment by JahnaviGadde** [comment]
@Saishreekouda checked and mentioned changes done 👍

**Pull request merged**
