### PR TITLE
Create anshgeez31.txt

### PR DESCRIPTION
**Pull request by anshgeez31**
Issue: 133

### CODE REVIEW

**Comment by Saishreekouda** [comment]
@anshgeez31 i have added a few comments in your figma file, please check.

**Comment by anshgeez31** [comment]
@Saishreekouda I have done the changes that you had mentioned. Please have a look.

**Comment by Saishreekouda** [comment]
@anshgeez31 please check once more

**Comment by anshgeez31** [comment]
@Saishreekouda have a look again.

**Pull request merged**
