### PR TITLE
Vector Design Task

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 107

vector design

### CODE REVIEW

**Comment by Saishreekouda** [comment]
@SanyamAgrawal07 you had to attach a picture in your pr

**Comment by Saishreekouda** [comment]
@SanyamAgrawal07 the idea is fine, but the box is an image and hence is not clear you will have to use svg format of that or make that vector.

**Comment by SanyamAgrawal07** [comment]
Oh sorry will take care of it from next time @Saishreekouda

**Comment by SanyamAgrawal07** [comment]
@Saishreekouda please review the changes

**Comment by Saishreekouda** [comment]
@SanyamAgrawal07 can you make a new pr and attach the txt file in the vector design folder

**Comment by SanyamAgrawal07** [comment]
sure

**Pull request closed without merging**
