### PR TITLE
Create ananyaa07.txt

### PR DESCRIPTION
**Pull request by ananyaa07**
Issue: 117

### CODE REVIEW

**Comment by Saishreekouda** [comment]
@ananyaa07 i have added a comment in your figma file, please check.

**Comment by ananyaa07** [comment]
@Saishreekouda I have modified a bit, you can check now

**Comment by ananyaa07** [comment]
@Saishreekouda The two things i have made beneath the shoes are basically how the shoes are kept in display in showrooms.

**Comment by Saishreekouda** [comment]
@ananyaa07 got it

**Pull request merged**
