### PR TITLE
Logo Design

### PR DESCRIPTION
**Pull request by Koshal7**
Issue: 58

image

### CODE REVIEW

**Comment by Saishreekouda** [comment]
@Koshal7 that hands looks quite creepy because of its sharp edges and the colors dont go with each other, so you might have to go through it once more

**Comment by Koshal7** [comment]
@Saishreekouda updated it.

**Comment by Saishreekouda** [comment]
The colors are fine now @Koshal7 but the hand does not look fine, you can either use a vector svg of the hand from google and add it to your logo if you want or make something different, as the logo now has a lot of elements which does not look nice.

**Comment by Koshal7** [comment]
@Saishreekouda updated it again

**Comment by Saishreekouda** [comment]
@Koshal7 remove the smile icon and then it will be fine

**Comment by Koshal7** [comment]
updated it, now can you merge this and review the home page design for oc bot

**Pull request merged**
