### PR TITLE
made the onboarding screens

### PR DESCRIPTION
**Pull request by humbleshashi8104**
issue: 30

made the onboarding screens with a signup and a login page screens.

### CODE REVIEW

**Comment by Saishreekouda** [comment]
hey @humbleshashi8104, there are a few changes that you have to do as these screens are not onboarding screens. You can ping me on discord if you want help. As this issue is closed now, you have time till 3pm to make these changes

**Comment by humbleshashi8104** [comment]
I need just 2 more hours, can u please give me the time , i'm working on it after doing a bit of research.

**Comment by Saishreekouda** [comment]
okay @humbleshashi8104 you have time till 5pm

**Comment by humbleshashi8104** [comment]
@Saishreekouda  ,please check my figma link, i have made the changes in it now.

**Pull request merged**
