### PR TITLE
Create anshgeez31.txt

### PR DESCRIPTION
**Pull request by anshgeez31**
Issue: 117
image

### CODE REVIEW

**Comment by Saishreekouda** [comment]
@anshgeez31 this is not related to sneakers in any way, so try a new approach

**Comment by anshgeez31** [comment]
@Saishreekouda Like Nike and any other brand logos are not at all depicting shoes but they are company logo so I took inspiration from that only.
Is it not correct ?

**Comment by Saishreekouda** [comment]
@anshgeez31 you can give an explanation of the logo and what it depicts, that would work too

**Comment by anshgeez31** [comment]
@Saishreekouda have a look

**Pull request merged**
