### PR TITLE
Create 2022019.txt

### PR DESCRIPTION
**Pull request by Rohit-110**
Issue: 133

image

### CODE REVIEW

**Comment by Saishreekouda** [comment]
can you join discord vc @Rohit-110 there are a few changes to be done

**Comment by Saishreekouda** [comment]
@Rohit-110 check the comments in your figma file

**Comment by Rohit-110** [comment]
I made the changes

**Comment by Rohit-110** [comment]
Ma'am I Made the changes

**Comment by Saishreekouda** [comment]
@Rohit-110 You can check again, a few more changes. You can join discord vc if you have any doubts

**Comment by Rohit-110** [comment]
Ma'am I did join Discord VC

**Pull request merged**
